### ISSUE TITLE
Reorganitzar resources

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#113]
Caldria separar com a mínim en:
* gui
* maps
* txt (tutorials i traduccions)
* missions (els xml)

**Comment by glaborda** [comment]
<img width="172" alt="captura de pantalla 2015-09-14 a las 13 26 56" src="https://cloud.githubusercontent.com/assets/3176709/9848758/51d9ad4c-5ae4-11e5-915f-0d4e06683f1d.png">
