### ISSUE TITLE
No mostrar cost si atribut a màxim nivell

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#130]
Ara mateix si està a nivell 5 surt a l'hexàgon un 6. Segurament caldria fer desaparèixer l'hex amb el cost i desactivar el signe de '+'.

**Comment by glaborda** [comment]
Vam quedar que restar punts tambe tenia cost, a no ser que ho canviem i el cost de cada nivell sigui fixe i restar sigui gratis.

**Comment by xrubio** [comment]
Tens raó!  Doncs ho deixem en desactivar els botons que no pots clicar (- a nivell 0 i + a nivell 5)?

**Comment by glaborda** [comment]
Jo ho deixaria aixi de moment, sempre som a temps de canviar-ho si la dinamica de joc ho necessita

**Comment by xrubio** [comment]
De fet ara té més interès el tema de restar punts, ja que els agents es mouen més ràpid amb la nova reproducció. Fas els botons només i tanques el issue?

**Comment by glaborda** [comment]
pero ja esta fet, no?
