### ISSUE TITLE
Arreglar Act::execute

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#131]
Ara mateix és molt raro perquè excepte Die totes les altres accions haurien de retornar void enlloc d'un iterator. Mirar com arreglar-ho.

**Comment by glaborda** [comment]
Si es fan dues passades (Die i resta d'accions) no cal que Die sigui herència de Act, no?

**Comment by xrubio** [comment]
Sí, pot ser una cosa a banda, faig el refactoring (crec que ara mateix ho he deixat amb bugs com #133 així que segurament s'arreglaran canviant això).
