### ISSUE TITLE
bug relacionat amb zoom

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#138]
Al fer zoom a l'escenari 3 (jugat per segon cop), segFault amb aquesta traça:

rogram received signal SIGSEGV, Segmentation fault.
0x00000000008a66e3 in UIGameplayMap::onMouseScroll (this=0x2149fe0, event=0x7fffffffd650) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/UIGameplayMap.cpp:928
928             float prevScaleX = gameplayMap->getScaleX();
(gdb) bt
#0  0x00000000008a66e3 in UIGameplayMap::onMouseScroll (this=0x2149fe0, event=0x7fffffffd650) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/UIGameplayMap.cpp:928
#1  0x00000000008b60ca in std::_Mem_fn<void (UIGameplayMap::*)(cocos2d::Event*)>::operator()<cocos2d::Event*, void>(UIGameplayMap*, cocos2d::Event*&&) const (this=0x218a540, 
    __object=0x2149fe0) at /usr/include/c++/4.9/functional:569
#2  0x00000000008b5a83 in std::_Bind<std::_Mem_fn<void (UIGameplayMap::*)(cocos2d::Event*)> (UIGameplayMap*, std::_Placeholder<1>)>::__call<void, cocos2d::Event*&&, 0ul, 1ul>(std::tuple<cocos2d::Event*&&>&&, std::_Index_tuple<0ul, 1ul>) (this=0x218a540, 
    __args=<unknown type in /home/xrubio/workspace/evPlanet/evolvingPlanet/bin/EvolvingPlanet, CU 0x1534a5, DIE 0x1a64fe>) at /usr/include/c++/4.9/functional:1264
#3  0x00000000008b4f35 in std::_Bind<std::_Mem_fn<void (UIGameplayMap::*)(cocos2d::Event*)> (UIGameplayMap*, std::_Placeholder<1>)>::operator()<cocos2d::Event*, void>(cocos2d::Event*&&) (this=0x218a540) at /usr/include/c++/4.9/functional:1323
#4  0x00000000008b40f6 in std::_Function_handler<void (cocos2d::Event*), std::_Bind<std::_Mem_fn<void (UIGameplayMap::*)(cocos2d::Event*)> (UIGameplayMap*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, cocos2d::Event*) (__functor=..., __args#0=0x7fffffffd650) at /usr/include/c++/4.9/functional:2039
#5  0x0000000000a6edad in std::function<void (cocos2d::Event*)>::operator()(cocos2d::Event*) const (this=0x3db8818, __args#0=0x7fffffffd650) at /usr/include/c++/4.9/functional:2439
#6  0x0000000000a7ebb6 in cocos2d::EventListenerMouse::<lambda(cocos2d::Event*)>::operator()(cocos2d::Event *) const (__closure=0x218a490, event=0x7fffffffd650)
    at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/base/CCEventListenerMouse.cpp:97
#7  0x0000000000a7ed88 in std::_Function_handler<void(cocos2d::Event*), cocos2d::EventListenerMouse::init()::<lambda(cocos2d::Event*)> >::_M_invoke(const std::_Any_data &, cocos2d::Event *) (__functor=..., __args#0=0x7fffffffd650) at /usr/include/c++/4.9/functional:2039
#8  0x0000000000a6edad in std::function<void (cocos2d::Event*)>::operator()(cocos2d::Event*) const (this=0x3db8770, __args#0=0x7fffffffd650) at /usr/include/c++/4.9/functional:2439
#9  0x0000000000a681e3 in cocos2d::EventDispatcher::<lambda(cocos2d::EventListener*)>::operator()(cocos2d::EventListener *) const (__closure=0x5852c30, listener=0x3db8750)
    at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/base/CCEventDispatcher.cpp:813
#10 0x0000000000a6a76a in std::_Function_handler<bool(cocos2d::EventListener*), cocos2d::EventDispatcher::dispatchEvent(cocos2d::Event*)::<lambda(cocos2d::EventListener*)> >::_M_invoke(const std::_Any_data &, cocos2d::EventListener *) (__functor=..., __args#0=0x3db8750) at /usr/include/c++/4.9/functional:2025
#11 0x0000000000a6ed5d in std::function<bool (cocos2d::EventListener*)>::operator()(cocos2d::EventListener*) const (this=0x7fffffffd5c0, __args#0=0x3db8750)
    at /usr/include/c++/4.9/functional:2439
#12 0x0000000000a6815a in cocos2d::EventDispatcher::dispatchEventToListeners(cocos2d::EventDispatcher::EventListenerVector*, std::function<bool (cocos2d::EventListener*)> const&) (
    this=0x10e9eb0, listeners=0x21861e0, onEvent=...) at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/base/CCEventDispatcher.cpp:776
#13 0x0000000000a68366 in cocos2d::EventDispatcher::dispatchEvent (this=0x10e9eb0, event=0x7fffffffd650)
    at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/base/CCEventDispatcher.cpp:817
#14 0x00000000009d1cd5 in cocos2d::GLViewImpl::onGLFWMouseScrollCallback (this=0x10eb530, window=0x1114670, x=0, y=1)
    at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:671
#15 0x00000000009d2607 in cocos2d::GLFWEventHandler::onGLFWMouseScrollCallback (window=0x1114670, x=0, y=1)
    at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:69
#16 0x00007ffff73a2f7b in _glfwInputScroll () from /usr/local/lib/libglfw.so.3
#17 0x00007ffff73ab62a in processEvent () from /usr/local/lib/libglfw.so.3
#18 0x00007ffff73ac703 in _glfwPlatformPollEvents () from /usr/local/lib/libglfw.so.3
#19 0x00007ffff73a5c14 in glfwPollEvents () from /usr/local/lib/libglfw.so.3
#20 0x00000000009d0e29 in cocos2d::GLViewImpl::pollEvents (this=0x10eb530)
    at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:455
#21 0x0000000000a5eae3 in cocos2d::Director::drawScene (this=0x10e75c0) at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/base/CCDirector.cpp:263
#22 0x0000000000a625da in cocos2d::DisplayLinkDirector::mainLoop (this=0x10e75c0) at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/base/CCDirector.cpp:1332
#23 0x00000000009c93d2 in cocos2d::Application::run (this=0x7fffffffd970) at /home/xrubio/workspace/evPlanet/evolvingPlanet/cocos2d/cocos/platform/linux/CCApplication-linux.cpp:86
#24 0x00000000008ef43b in main (argc=1, argv=0x7fffffffda88) at /home/xrubio/workspace/evPlanet/evolvingPlanet/proj.linux/main.cpp:14

**Comment by miquelramirez** [comment]
Possibly the same bug - I got a crash while zooming out during the Tutorial section of level/map 2.
