### ISSUE TITLE
Objectius en posició errònia al refer

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#141]
El mateix que #140 suposo...alguna cosa a veure amb l'init?

![objectius](https://cloud.githubusercontent.com/assets/1416266/10333928/363ac944-6ce7-11e5-8ee1-1f1d7d3a1716.png)

**Comment by glaborda** [comment]
si

**Comment by xrubio** [comment]
Sembla que passa de manera aleatòria després de passar-se la missió 1.
