### ISSUE TITLE
Moure il·lustracions dels briefings a Achievements

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#145]
Haurien de mostrar-se quan el jugador es passa el nivell enlloc del briefing, i aleshores estar disponibles en una Galeria (potser dins dels Achievements?).

**Comment by glaborda** [comment]
Com s'hauria de mostrar al final del nivell? A una escena nova de transició al UIProgressMap o junt amb el missatge al passar-se el nivell? S'hauria de fer cada cop que te'l passis o només el primer cop?

**Comment by xrubio** [comment]
Ha passat a ser la història #174
