### ISSUE TITLE
3er objectiu de missió 2 no acomplert encara que els agents estiguin en ell

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#152]
En general els objectius sovint no es mostren a on toca.

![objectius_no_comprovats](https://cloud.githubusercontent.com/assets/1416266/10795185/d6b95874-7d98-11e5-9c99-a70f1aa7fed3.png)

**Comment by glaborda** [comment]
Es el que et deia, al canviar que nomes comproves el proxim objectiu va com vol
