### ISSUE TITLE
Catalan language support and cocos2d 3.8.1

### ISSUE THREAD

**Issue by miquelramirez** [xrubio/simulplay#162]
Hello,

I got this error while compiling simulplay against cocos2d 3.8.1

> cocos2d-x-3.8.1/simulplay/Classes/LocalizedString.cpp: In static member function ‘static const char* LocalizedString::getSystemLang()’:
> cocos2d-x-3.8.1/simulplay/Classes/LocalizedString.cpp:76:10: error: ‘CATALAN’ is not a member of ‘cocos2d::LanguageType’
>     case LanguageType::CATALAN:

Is there perhaps a missing step in the guide docs/installLinux?

**Comment by xrubio** [comment]
You are right, there was a missing step in the doc (you need to copy a couple of cpp files to cocos installation)
