### ISSUE TITLE
A vegades peta de manera aleatòria

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#190]
Potser per temes de memòria? Està confirmat en tablets android però potser també passa en ipad.

**Comment by glaborda** [comment]
A iPad al jito tambe li va passar

**Comment by glaborda** [comment]
relacionat #181 ?

**Comment by glaborda** [comment]
644MB -> 22min -> 10 levels jugats

**Comment by xrubio** [comment]
Tema de threads, solucionat (esperem)
