### ISSUE TITLE
Definir nous atributs i poders per missions 11-20

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#192]
Com a mínim caldria definir un per transformar el territori (agricultura).

**Comment by glaborda** [comment]
Si no recordo malament en vaig fer un que era d'area, que recuperava una zona destrossada. No se si sera facil recuperarlo, pero es podria tornar a fer

**Comment by xrubio** [comment]
Iep que també són atributs, m'he empanat xD
