### ISSUE TITLE
Acció Terraform

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#200]
Aquesta acció transforma la zona del mapa a on està un bot per tal de baixar el cost en resistència (i per tant augmentar la població).
Engloba activitats d'agricultura, ramaderia i pesca.
No es pot fer a totes les zones (per exemple, a muntanya no es pot)
A nivell de mapa es canvia el pixel per un mapa a on la zona sembli transformada (per exemple posant canals, zones cultivades, ports o barquetes, etc.).

**Comment by glaborda** [comment]
Plantejar:
  - Canviar resistencia mitjançant una funcio o obtenir valors del mapa (B, > 10)
  - Matriu per guardar terraformats
  - Com saber si una zona es terraformable. Una opcio es mirar si B > 10
  - Com dibuixar el mapa terraformat (no limitar-se a la zona terraformada, el mapa ha de tenir una mica de marge). Guardar transparencies? Suposar que sempre es posen a 255?  (Parlar-ho amb el david)
