### ISSUE TITLE
La capa de recursos no es pinta bé a Android

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#235]
Deu ser alguna cosa relacionada amb la creació de la textura (mirar captura).

![screenshot_2015-12-22-12-54-35](https://cloud.githubusercontent.com/assets/1416266/11955181/d31cd924-a8af-11e5-89a9-b9dc29a100bf.png)

**Comment by glaborda** [comment]
No és error d'android, el problema és quan la mida de la pantalla no coincideix amb el de la imatge.
És degut a que actualment es carrega la imatge en una matriu de la mida de les dades de la imatge (sempre fixe en funció de la mida de la imatge). 
Quan és carrega una imatge de mida diferent, no coincideixen els pixels i es pinta la imatge estirada. El problema és que si la mida varia, ens hauriem d'inventar els pixels de diferència de la imatge a la matriu, ja que no existirien.
