### ISSUE TITLE
Els agents que no tenen 1 recurs no es veuen

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#251]
A la imatge, al canviar d'objetiu 1 a 2 (fusta a mineral) els agents que surten del bosc no es veuen.

![invisible](https://cloud.githubusercontent.com/assets/1416266/12169809/b932da34-b53b-11e5-857e-fd67be5ea827.png)

**Comment by glaborda** [comment]
Son de color gris. El tema es que quan tries un material s'enfosqueix el color de la vida dels que no tenen aquell material.

**Comment by xrubio** [comment]
I si pintem els agents del color del recurs que tenen, o del color standard si no en tenen cap? Ara mateix no s'entén el que mires (és rollo fantasma).

**Comment by xrubio** [comment]
O una alternativa...i si passem del tema? Al final saps que tens recursos per la barra de sota a la dreta, aixi que no tinc clar que calgui pintar els agents.

**Comment by glaborda** [comment]
Si pintem els agents del color del recurs, quan es barregin dos tipus diferent d'agents no es distingiran.
Per altra banda, si passem, i hi ha mes d'una poblacio rival, es dificil saber quina te quin recurs. Les missions s'haurien de fer bastant tancades, forçant el trobament de les poblacions que tinguin el recurs necessari en el moment d'assolir l'objectiu indicat. O be que el jugador ho descobreixi a prova i error.

**Comment by xrubio** [comment]
Sí però ara mateix al veure que una població està consumint una zona de mineral o de fusta, ja saps que estan recollint aquest material no?

**Comment by glaborda** [comment]
Si. Podem posar al tutorial que siguin observadors. O a la hint del nivell dir quin tipus d'agent te que.
