### ISSUE TITLE
La visualització dels agents amb recursos és molt confusa

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#253]
Parcialment relacionat amb #251 .
No s'aprecia gens quin agent té quina matèria.
Veig 2 opcions (si n'hi ha més editar el issue):
* Ho eliminem i llestos (total, les missions no són tan complexes)
* Sempre que s'estigui mirant un recurs i no la població, pintar tots els agents del color del recurs que tinguin (i no només el recurs observat).

![Uploading caos.png…]()

**Comment by glaborda** [comment]
Es pot donar el cas que no tinguis prou agents per representar tots els recursos (actualment passa) o tipus de recursos alhora.
Per solucionar el #251 senzillament es pot pintar normal..
