### ISSUE TITLE
Comportament asimètric amb Hint

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#254]
Quan s'apreta el botó de hint el joc es posa en pausa i es mostra el hint. Si es torna a pretar s'amaga el hint, però el joc segueix en pausa. Seria millor si el joc torna a play en aquell moment.

**Comment by glaborda** [comment]
Llavors si l'apretes durant pausa, el hint fa de play. Correcte?

**Comment by xrubio** [comment]
Ui això també seria confús...no podria tornar a l'estat anterior?

* Si està en play aleshores pausa el joc, i el segon cop el torna a play
* Si està en pausa, aleshores es mostra el hint, i el segon cop l'amaga (però mantenint-te en pausa).
