### ISSUE TITLE
La nau no arriba a lloc al main menu

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#257]
A vegades al picar en un botó, després que aparegui, no entra a on toca (continue, new game...). Al mateix temps sembla que la nau es mou una mica cap a la dreta, com si estiguessis saltant-te l'animació (que en teoria ja està acabada o no sortirien els botons).

**Comment by glaborda** [comment]
Entenc que es perque no ha acabat el fade in. La idea llavors es que quan la opacitat dels botons sigui suficient com per que es vegi el boto, es pugui clicar.

**Comment by xrubio** [comment]
Però tingues en compte que passa molt després que acabi el fade in (rollo 10 segons des que es mostren els botons).
