### ISSUE TITLE
A vegades no saps si ja has passat un objectiu

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#259]
El canvi d'un objectiu al següent no es mostra en pantalla. Es podria mostrar durant pocs segons una label que posi "1/2 Goals Completed" o similar, o fer alguna animació per a que el jugador vegi clarament que ja ha assolit l'objectiu.

**Comment by glaborda** [comment]
Potser podriem marcar l'objectiu actual amb les fletxetes del tutorial?
Quan es canvii d'objectiu, marquem el tipus iluminant la zona de dispersio o la grafica en cas de poblacio o recursos?
