### ISSUE TITLE
Retry hauria de comptar per ensenyar el hint

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#274]
Retry ha de comptar igual que una missió fallida (molta gent farà retry quan ho vegi tot perdut).

**Comment by glaborda** [comment]
jo crec que no, tho compro si li afegim un num dsteps minim

**Comment by xrubio** [comment]
Ok, si ha passat el 20% de la missió el fem comptar?

**Comment by xrubio** [comment]
Ho ignorem per ara
