### ISSUE TITLE
El canvi de capa per resources/terraform a vegades deixa pixels negres

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#276]
Ha de tenir a veure amb la superposició de les capes (mirar al centre a la dreta, just sobre el bosc).
![punts_negres](https://cloud.githubusercontent.com/assets/1416266/12451848/c7977e68-bf8b-11e5-983d-7c62ffa3668c.png)

**Comment by glaborda** [comment]
te a veure amb els diferents nivells de transparencia, nomes nhi hauria dhaver dos, ja li vaig comentar al david

**Comment by glaborda** [comment]
#268
