### ISSUE TITLE
Al sortir amb 'home' i entrar els bots morts es queden en pantalla

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#292]
Es veu a la imatge, potser cal cridar a l'updateAgents amb transparent de nou?

![screenshot_2016-01-29-15-48-56](https://cloud.githubusercontent.com/assets/1416266/12678654/20ce5da6-c6a0-11e5-97e2-15daaefad9fc.png)

**Comment by glaborda** [comment]
i si despres de posar en pause crides updateAgents desde AppDelegate perque faci el darrer pintat que esborrara els agents?

**Comment by xrubio** [comment]
A on està aquest codi? No veig a on es pausa el joc a AppDelegate (surt stopAnimation només)
