### ISSUE TITLE
Resposta lenta a canvi de nivell

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#41]
Al mapa general sovint selecciones un nivell i no passa res.
Pot ser que sigui perquè és una llista de 'level 1', 'level 2', ... i al tocar el sistema no sap quin level s'ha seleccionat?

Suggeriria fer la selecció diferent (botons separats?).

**Comment by glaborda** [comment]
Crec que es deu a un problema de precisió, ja sigui perquè els labels estan massa junts o són massa petits. Li comentaré al david a veure si se li acud algun altre sistema més adequat

**Comment by xrubio** [comment]
Pozi jo diria que és un problema d'interfície...a desktop va de puta mare però en una tablet això de la llista de text no funciona...

**Comment by glaborda** [comment]
Cal seleccionar els llocs on carregar els mapes mes pesats ja que poden ralentitzar el joc en algun moment com per exemple animació inicial, selecció de nivell a la llista, o selecció de nivell al mapa.
#42
