### ISSUE TITLE
Primera selecció lenta

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#42]
El primer cop que es toca qualsevol botó va molt lent. El segon ja va molt més ràpid (possiblement sigui un tema de carregar coses a memòria?)

Es pot veure clarament amb el botó inicial de 'Start' a la pantalla inicial del joc.

Hi ha manera d'accelerar-ho, per exemple fer precàrrega a memòria?

**Comment by glaborda** [comment]
Provar si es nota la diferència. De ser així, s'hauria de fer la gestió de precàrregues d'imatges i alliberament en funció dels mapes.
