### ISSUE TITLE
Inici de nivell en pausa

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#45]
Crec que tots els nivells haurien de començar en pausa. Al mateix temps, quan s'està en pausa enmig de la pantalla (o potser a la barra de temps?) hauria de sortir un missatge clar "PAUSE".

**Comment by glaborda** [comment]
Proposo un enfosquiment del mapa amb unes lletres amb transparència per sobre que posi PAUSE

**Comment by xrubio** [comment]
ok em sembla bé, pots fer el canvi?

**Comment by glaborda** [comment]
si, demà al matí revisaré tots els issues.
