### ISSUE TITLE
'Quit' no funciona

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#46]
Si selecciones la x a la pantalla de joc i confirmes el joc es penja.

**Comment by xrubio** [comment]
Acabo de veure que el Retry fa el mateix.

**Comment by xrubio** [comment]
Com a nota addicional, a Linux no passa.

**Comment by glaborda** [comment]
Segons he provat, crec que nomes falla quan tens els dos quadrets (de retry i quit) mostrant-se alhora

**Comment by xrubio** [comment]
No, a mí a l'ipad 3 em passa sempre...igual està relacionat amb que el joc no s'actualitzi (algun rollo d'eficiència?).

**Comment by xrubio** [comment]
Estava relacionat amb l'issue #49 , doncs al solucionar-se una cosa també funciona l'altra.
