### ISSUE TITLE
Els agents no s'actualitzen

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#49]
Els agents es queden a la posició inicial i no passa res en cap dels escenaris, ni accelerant el ritme (botó >>). Això em passa a tots els nivells.

**Comment by xrubio** [comment]
De fet, al acabar-se el temps tampoc surt cap pantalla, potser no s'està executant el motor?

**Comment by xrubio** [comment]
Confirmo que només passa a Ipad 3, probablement eficiència?

**Comment by xrubio** [comment]
Ara sí que ho fan...abans de tancar issue, quin era el problema?

**Comment by glaborda** [comment]
No he fet res perquè a mi no em passava i no sabia que mirar..

**Comment by xrubio** [comment]
Sembla que està relacionat amb la versió de TestFlight; potser és cosa de flags de debug, que va massa lent?

**Comment by glaborda** [comment]
Només funciona bé quan es compila amb mode Debug (per defecte des de l'Xcode). Compilant amb Release no funciona (per defecte quan es fa Archive -> Testflight)

**Comment by glaborda** [comment]
Problema: el refresc de pantalla es massa ràpid i el flag "play" (controlat pel render) pasa de false a true massa ràpid, la qual cosa fa que no es s'executi el motor de joc. 

Solució 1: Baixant els fps es soluciona la sincronització. S'ha de comprovar que no afecti a altres aspectes del joc com poden ser animacions.

**Comment by xrubio** [comment]
Ok, el tanco doncs?

**Comment by xrubio** [comment]
Amb ipad 3 segueix passant amb la nova versió del TestFlight, però no es del principi (probablement el primer cop que salta ja es queda clavat). També es reprodueix el bug #46
