### ISSUE TITLE
Passar de pàgina 3 a 2 al briefing clicant a la dreta

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#53]
**Si**
* Estàs a la pàgina 3 del briefing (la dels punts d'evolució
* Cliques a la zona aproximada a on està la fletxa cap a la dreta (que aquí no apareix, es clar).

**Efecte**
* A vegades torna a la pàgina 2.

**Comment by glaborda** [comment]
Passa només a la zona aproximada de la fletxa que descrius o en qualsevol lloc i en qualsevol pàgina?
Arrastres el cursor/dit o només cliques sense variar absolutament gens la posició?
Si és així, intueixo que deu ser la sensibilitat de moviment del canvi de pàgina.

**Comment by xrubio** [comment]
Passa en els 2/3 de drets de la pantalla, no és exactament a on està la fletxa.
D'altra banda, el bug és tan a linux com ipad3.

**Comment by xrubio** [comment]
Està relacionat amb el pan arrastrant la pantalla (si és 1 píxel o més ja canvia).
