### ISSUE TITLE
Sortir del joc a desktop

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#54]
Cal un 'quit' en algun lloc des del menú inicial per sortir del joc quan jugues a desktop.

**Comment by glaborda** [comment]
Perfect, està implementat però amagat. El mostro per android i W8 també?
(A les darreres versions de cocos2dx hi ha per compilar per W8)

**Comment by xrubio** [comment]
Mm a android és igual que ios no? Jo ho faria només per desktop
(linux/mac/w8).

El dia 14 de juny de 2015, 16:22, glaborda <notifications@github.com> ha
escrit:
