### ISSUE TITLE
estela de la nau (pantalla inicial)

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#57]
**Si:**
* estàs a la pantalla inicial
* toques la pantalla per saltar-te l'animació

**Problema:**
* la nau salta automàticament al final, però la primera estela de la nau es queda allà fins que acaba l'animació

**Fix:**
Queda raro, es podrien tancar totes les animacions si es toca la pantalla?

**Comment by xrubio** [comment]
Una imatge de l'efecte raro.
![estela](https://cloud.githubusercontent.com/assets/1416266/8265834/ea9bddba-16c0-11e5-8647-ed76c01a8800.png)

**Comment by glaborda** [comment]
He fet un arreglo parant i resetejant el sistema de particules. Així no deixa rastre.
