### ISSUE TITLE
objectiu erroni

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#58]
**Condicions**
* Escenari 1
* Es posa el marcador a la zona del primer objectiu

**Problema**
* els agents es mouen cap a una península a l'oest de l'objectiu i es queden encallats (veure imatge)

![objectiu_erroni](https://cloud.githubusercontent.com/assets/1416266/8265796/ceedda92-16bf-11e5-9503-62bc4073cc0b.png)

**Comment by glaborda** [comment]
L'error està en la conversió del punt de l'indicador al punt del mapa.
