### ISSUE TITLE
Poders a +6

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#69]
**Si:**
* un poder arriba al màxim

**Problema:**
* No saps si pots continuar pujant-los (tot està activat però donar-li al botó no fa res).

**Fix:**
* Potser desactivar el botó?
![podera6](https://cloud.githubusercontent.com/assets/1416266/8269043/ea053f86-174c-11e5-8012-172c52c54ba3.png)

**Comment by glaborda** [comment]
Els botons de + i - es desactivaran en funció de si s'arriba al màxim, de si estan al mínim o de si es tenen suficients punts d'evolució.
