### ISSUE TITLE
Els agents es comporten raros a la costa

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#70]
Es pot veure en aquesta imatge.
![raro_costa](https://cloud.githubusercontent.com/assets/1416266/8269044/11ab7992-174d-11e5-99c4-610a1fc43247.png)

**Comment by glaborda** [comment]
Diria que es conseqüència dels mapes de fons. Com darrerament me n'enviaven de nous molt sovint no feia el mapa de fons cada cop i deu ser una versió més antiga.
