### ISSUE TITLE
Continue/Iniciar nova campanya

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#73]
Caldria permetre a l'usuari iniciar una nova campanya (esborrant l'anterior) o ara bé continuar amb la que tenia. A la pantalla inicial hi hauria d'haver els botons:

* **Continue** (activat si ja hi ha alguna cosa guardada, si s'ha donat al reset o és el 1er cop ha d'estar desactivat'
* **New campaign** (si s'apreta, surt box amb sí/no per la pregunta: 'començar una nova campanya esborrarà el progrés actual. Estàs segur que vols continuar?')
* **Achievements**

I a sota:
* **Configuration**
* **Crèdits**
* **Exit** (si s'està a desktop, no a tablet)

**Comment by glaborda** [comment]
Actualment es pot resetejar el progrés de joc a Configuration -> Reset.
Em sembla bé fer el canvi, però el botó de Continue el faria invisible el primer cop que es jugui i l'afegiria un cop es comenci la campanya per primera vegada. Òbviament el primer cop que es jugui no es farà la pregunta d'esborrar.

S'hauria de fer una petita intro o alguna cosa cada cop que es comenci una campanya? o senzillament anar al mapa?

**Comment by xrubio** [comment]
Ok al tema del continue, em sembla bé el que proposes.
Sobre la intro, molaria fer alguna cosa, encara que siguin 20 segons amb imatges estàtiques desplaçant-se (com el menú principal).

**Comment by glaborda** [comment]
He fet una interficie amb lo que havia fet el david i la funcionalitat. Falta alguna idea d'intro.
El continue estarà amagat només quan es jugui per primer cop i no es cliqui mai el de nova campanya. Un cop es comença una campanya (encara que no s'hagi jugat cap partida), al tornar enrere, sortirà el botó de continuar per no haver de clicar cada cop nova campanya i haver de passar per la intro.
