### ISSUE TITLE
Sèrie temporal amb número d'agents

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#74]
**Problema**
Mentre jugues és molt confús saber si la teva població està incrementant-se, està al límit o s'està morint.

**Fix**
En algun lloc de la interfície hi hauria d'haver una mini línia mostrant la tendència, rollo [línia marcant les senyals vitals](http://www.pd4pic.com/images/-medical-pulse-pulse-trace-heartbeat-graph.png). A més, si hi ha més d'un tipus d'agents pot sortir cada línia d'un color.

**Comment by glaborda** [comment]
Potser podriem aprofitar la part de baix (substituir els labels d'atributs que canvien el color dels agents) per ficar aquestes línes o indicadors que es vagin omplint o buidant en funció de la quantitat de població. Així també es podria conèixer si s'ha arribat al límit de població.

**Comment by xrubio** [comment]
Sí, és el que jo pensava...ho proves aviam?

**Comment by xrubio** [comment]
Duplicat amb #93
