### ISSUE TITLE
pixel size a config de cada nivell

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#76]
Ara mateix pixel size per nivell està hardcoded:
https://github.com/xrubio/simulplay/blob/master/Classes/UIProgressMap.cpp#L533

Es pot moure al xml de cada nivell, i canviar el if iterat per 'level'+to_string(tag).

**Comment by glaborda** [comment]
El pixel size anirà en funció de com es pintin els agents, i dependrà també de la mida del nivell. Potser si és massa petit no cal fer més d'una mida. De moment és per fer proves

**Comment by xrubio** [comment]
Ok però si es decideix deixar-lo millor passar-ho a xml no?
