### ISSUE TITLE
Ev. points a l'inici de l'escenari

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#81]
Quan es comença a jugar un nivell (al mapa) caldria resetejar a 0 els punts d'evolució disponibles. Actualment si no gastes algun punt al Briefing, es trasllada directament al mapa.

**Comment by glaborda** [comment]
No deixem que el jugador es pugui guardar punts per després?

**Comment by xrubio** [comment]
Jo diria que millor no? Si no, quin sentit té posar punts abans de començar? O això, o directament eliminem la pantalla de punts del briefing. Com l'escenari comença en pausa, el jugador distribueix els punts i tirando. Què et sembla?

**Comment by glaborda** [comment]
El tema és que els agents inicials, quan es coloquen al mapa, ja tenen els atributs amb els valors que ha escollit el jugador. 
Es podria fer això d'eliminar-ho del briefing i actualitzar els agents ja col·locats amb els setters un cop li doni play (de fet, un dels problemes pels que triga més en començar el nivell quan es clica start, i que de moment no precalculem fins el clic  perquè esperem a saber els valors dels atributs, és la col·locació dels agents inicials a l'escenari). 
Tot i així crec que hauriem d'explicar els atributs que utilitzarà durant el nivell per saber que es trobarà. O potser no... no sé

**Comment by xrubio** [comment]
Ok ho parlem perquè ara mateix ho veig redundant, doncs en els 2 casos estàs modificant el mateix (des del punt de vista del jugador).
