### ISSUE TITLE
Al clicar 2 cops no pots definir el marcador al mapa.

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#87]
Segurament relacionat amb els canvis de #58 ?
Em passa al PC de casa (Linux) però no al laptop (Linux a mac).

**Comment by xrubio** [comment]
A vegades sí que el marques (potser 1 cop de cada 5...).

**Comment by glaborda** [comment]
A mi al portàtil amb linux no em passa. Pot ser que sigui degut al temps entre el primer clic i el segon? Si cliques molt ràpid et segueix sense funcionar? Et passa en algun nivell en concret?
