### ISSUE TITLE
zoom a pc peta

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#89]
Amb aquest missatge:

Assert failed: CCNode#scale. ScaleX != ScaleY. Don't know which one to return
EvolvingPlanet: /home/xrubio/workspace/evPlanet/EvolvingPlanet/cocos2d/cocos/2d/CCNode.cpp:466: virtual float cocos2d::Node::getScale() const: Assertion `_scaleX == _scaleY' failed.

**Comment by xrubio** [comment]
Iep segueix petant amb el mateix missatge. Pot estar relacionat amb les mides de la pantalla?

**Comment by glaborda** [comment]
L'error es dóna quan es fa un getScale i la X i Y són diferents, llavors no sap que tornar, si X o Y. La modificació que vaig fer és substituir el getScale per getScaleX o getScaleY ja que potser l'escalat era diferent segons la mida de la pantalla. Et peta només a pc?
