### ISSUE TITLE
CC_PLATFORM_WP8 not found

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#90]
error de compilació aquí:
https://github.com/xrubio/simulplay/blob/master/Classes/UIMainMenu.cpp#L170
No trobo el define a on estan la resta (a cocos2d/cocos/platform/CCPlatformConfig.h). D'on surt això...?

**Comment by glaborda** [comment]
quina versió de cocos fas servir? jo compilant amb la 3.6 em funciona (fa pocs dies va sortir la 3.8 rc0)

// define supported target platform macro which CC uses.
#define CC_PLATFORM_UNKNOWN            0
#define CC_PLATFORM_IOS                1
#define CC_PLATFORM_ANDROID            2
#define CC_PLATFORM_WIN32              3
#define CC_PLATFORM_MARMALADE          4
#define CC_PLATFORM_LINUX              5
#define CC_PLATFORM_BADA               6
#define CC_PLATFORM_BLACKBERRY         7
#define CC_PLATFORM_MAC                8
#define CC_PLATFORM_NACL               9
#define CC_PLATFORM_EMSCRIPTEN        10
#define CC_PLATFORM_TIZEN             11
#define CC_PLATFORM_QT5               12
#define CC_PLATFORM_WP8               13
#define CC_PLATFORM_WINRT             14
