### ISSUE TITLE
Botó expansió atributs desapareix a vegades

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#91]
Ni idea, ho he fet 2 cops i el segon va correctament (mirar pantallazo).

![andehaido](https://cloud.githubusercontent.com/assets/1416266/9659673/f878b8fa-5251-11e5-84e5-73c2ffdeed1b.png)

**Comment by glaborda** [comment]
Passa quan cliques dos cops molt rapid sense que s'hagi acabat l'animacio i per tant, s'enva dos cops cap a la dreta i desapareix. S'arregla comprovant que s'hagin acabat les accions del boto.
