### ISSUE TITLE
Combinar Pause/Play

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#94]
No té sentit gastar GUI en posar 2 botons, es podria fer que el botó canviés de pause a play al prèmer, i viceversa.

**Comment by xrubio** [comment]
És més; cal que tinguem play i fast forward? Jo sempre li dóno al fast forward...i els només tenim 1 botó de play/pause?

**Comment by glaborda** [comment]
Estic d'acord. Lo del pause/play es podria canviar ja, pero per debugar (per saber si hi ha problemes de temps de calcul i poder donar mes marge) de moment deixaria el play i el ff

**Comment by xrubio** [comment]
Mecànica corregida (falta GUI, mencionat a #101)
