### ISSUE TITLE
Tornar a mapa base general després de cada missatge

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#95]
Això evitaria problemes amb el zoom/pan al assenyalar coses.

**Comment by glaborda** [comment]
Per assenyalar coses i que no es moguin i s'escalin al fer pan o zoom senzillament s'han d'afegir com a fill del gameplayMap

**Comment by xrubio** [comment]
Tancat a commit d1236c17d9a09903d7bb37b8e550aa5c5ba3ca8b
