### ISSUE TITLE
segFault random

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#97]
Al nivell 2 m'ha donat un segFault al fer zoom (crec), a finals de l'escenari.

**Comment by glaborda** [comment]
A mi m'acaba de passar al passar el segon objectiu

**Comment by xrubio** [comment]
A mí també, al intentar pujar un atribut. Vaig a mirar si és el nou codi del Tutorial.

**Comment by xrubio** [comment]
Sembla que no; enllaço el backtrace del segFault...algun caràcter que no està a la FontAtlas??

[traça](https://gist.github.com/xrubio/ace0d0b24741d8c4ec63)
